import {StyleSheet} from 'react-native';
import {
  moderateScale,
  scaledSize,
  scaleHeight,
  scaleWidth,
} from '../../utils/dimensions';
import { Colors } from '../../theme';
export const styles = StyleSheet.create({
  confirmTxt: {
    fontWeight: '700',
    fontSize: scaledSize(24),
    lineHeight: scaleHeight(28.13),
    textAlign: 'center',
    color: Colors.LIGHT_PURPLE,
    position: 'absolute',
    bottom: scaleHeight(628),
    width: '100%',
  },
  phoneTxt: {
    fontSize: scaledSize(16),
    lineHeight: scaleHeight(18.75),
    textAlign: 'center',
    color: '#8A8D9F',
  },
  container_box: {},
  boxTxt: {
    backgroundColor:Colors.WHITE,
    width: scaleWidth(66),
    height: scaleHeight(66),
    borderRadius: 10,
    textAlign: 'center',
    color: '#242A37',
    fontWeight: '400',
    fontSize: scaledSize(18),
    lineHeight: scaleHeight(21),
  },
  line: {
    backgroundColor: '#242A37',
    width: scaleWidth(46),
    height: scaleHeight(2),
    alignSelf: 'center',
  },
  otp_Box: {
    position: 'absolute',
    bottom: scaleHeight(488),
    flexDirection: 'row',

    alignItems: 'center',
    justifyContent: 'center',
    width: '100%',
    gap: moderateScale(11),
  },
  timeTxt: {
    position: 'absolute',
    bottom: scaleHeight(413),
    width: '100%',
    textAlign: 'center',
    fontSize: scaledSize(16),
    lineHeight: 18.75,
    fontWeight: '500',
    color: '#23D2C3',
  },
  button: {
    alignSelf: 'center',
    backgroundColor: 'transparent',
    alignItems: 'center',
    borderRadius: 25,
    position: 'absolute',
    top: scaleHeight(419),
    width: scaleWidth(295),
    backgroundColor: 'red',
  },
  containerBtn: {
    elevation: 8,
    borderRadius: 25,
    width: '100%',
    height: scaleHeight(50),
    borderRadius: 25,
    justifyContent: 'center',
  },
  resendBox: {
    flexDirection: 'row',
    position: 'absolute',
    bottom: scaleHeight(444),
    alignSelf: 'center',
    alignItems: 'center',
    gap: 4,
  },
});
